[workspace]
members = [
    "app",
    "core",
    "references/iroh-gossip",
    "references/iroh-h3/iroh-h3-axum",
    "references/iroh-h3/iroh-h3-client",
    "references/iroh-h3/iroh-h3",
]
resolver = "2"
